#Home Login pages
print("----------------------------------------")
print("Welcome to Miracle Application V.1223")
print("----------------------------------------")
usernameInput = input("Username : ")
passwordInput = input("Password : ")

#Catalog when login success
if usernameInput == "admin" and passwordInput == "1234":
    print("----------------------------------------")
    print("Login success !! Welcome to Miracle shop")
    print("----------------------------------------")
    print("Product list")
    print("- 1. Steam wallet  150 THB")
    print("- 2. Steam wallet  300 THB")
    print("- 3. Steam wallet  750 THB")
    print("- 4. Steam wallet 1500 THB")
    print("- 5. Steam wallet 3000 THB")
    print("----------------------------------------")
    print("Which item do you want to buy ?")
    print("Choose Number 1-5")
    userSelected = int(input(">>> : "))
    if userSelected == 1:
        print("----------------------------------------")
        print("Selected item : Steam wallet  150 THB")
        print("----------------------------------------")
        print("What's the order quantity ?")
        amount1 = int(input(">>> : "))
        p1      = 150       #p1 = price of goods 1
        result1 = (p1*amount1)
        print("----------------------------------------")
        print("#Order list")
        print("- Steam wallet 150 THB x", amount1 ,":", result1,"THB")
        print("----------------------------------------")
        print("Thank you for shopping with us :)")
    elif userSelected == 2:
        print("----------------------------------------")
        print("Selected item : Steam wallet  300 THB")
        print("----------------------------------------")
        print("What's the order quantity ?")
        amount2 = int(input(">>> : "))
        p2      = 300       #p2 = price of goods 2
        result2 = (p2*amount2)
        print("----------------------------------------")
        print("#Order list")
        print("- Steam wallet 300 THB x", amount2 ,":", result2,"THB")
        print("----------------------------------------")
        print("Thank you for shopping with us :)")
    elif userSelected == 3:
        print("----------------------------------------")
        print("Selected item : Steam wallet  750 THB")
        print("----------------------------------------")
        print("What's the order quantity ?")
        amount3 = int(input(">>> : "))
        p3      = 750       #p3 = price of goods 3
        result3 = (p3*amount3)
        print("----------------------------------------")
        print("#Order list")
        print("- Steam wallet 750 THB x", amount3 ,":", result3,"THB")
        print("----------------------------------------")
        print("Thank you for shopping with us :)")
    elif userSelected == 4:
        print("----------------------------------------")
        print("Selected item : Steam wallet  1500 THB")
        print("----------------------------------------")
        print("What's the order quantity ?")
        amount4 = int(input(">>> : "))
        p4      = 1500      #p4 = price of goods 4
        result4 = (p4*amount4)
        print("----------------------------------------")
        print("#Order list")
        print("- Steam wallet 1500 THB x", amount4 ,":", result4,"THB")
        print("----------------------------------------")
        print("Thank you for shopping with us :)")
    elif userSelected == 5:
        print("----------------------------------------")
        print("Selected item : Steam wallet  3000 THB")
        print("----------------------------------------")
        print("What's the order quantity ?")
        amount5 = int(input(">>> : "))
        p5      = 3000      #p5 = price of goods 5
        result5 = (p5*amount5)
        print("----------------------------------------")
        print("#Order list")
        print("- Steam wallet 3000 THB x", amount5 ,":", result5,"THB")
        print("----------------------------------------")
        print("Thank you for shopping with us :)")
    else:
        print("----------------------------------------")
        print("The number you entered is not in the list.")
        print(" > > > > > Please try again < < < < < ")
        print("----------------------------------------")
else:   #Error when wrong ID or PSW
    print("----------------------------------------")
    print("The username or password is incorrect.")
    print(" > > > > > Please try again < < < < < ")
    print("----------------------------------------")